---
- hosts: local
  become: no
  gather_facts: False
  vars:
  tasks:
    - name: Deploy OVA file to Vsphare
      vmware_deploy_ovf:
        hostname: <vsphare hostname/IP>
        username: vsphare_username
        password: vsphare_password
        validate_certs: no
        name: VMware-vIDM
        datacenter: data_center
        folder: folder
        cluster: cluster_name
        datastore: datastore_on_vsphare
        disk_provisioning: thin
        networks:
          "Network 1": Management
        ova: ove_file_path
        allow_duplicates: no
        power_on: yes
        fail_on_spec_warnings: yes
        wait: yes
        wait_for_ip_address: yes
        inject_ovf_env: yes
      delegate_to: localhost
